import Link from 'next/link';
import { ArrowDown, ArrowUpRight } from 'lucide-react';
import { Action, CTASection, PackageCard, ProcessFlow, SectionHeading, ServiceCard, StatBlock } from '@/components/site/primitives';
import { HeroWords, Reveal } from '@/components/site/client';
import { packages, services, stats } from '@/content/site';
export default function Home(){return <>
<section className="home-hero"><div className="hero-grid wrap"><div className="hero-copy"><span className="eyebrow">STRATEGIC THINKING. CREATIVE POSSIBILITY.</span><HeroWords/><p className="hero-tagline">From Ideas to Impact.<br/>From Impact to Influence.</p><p className="hero-body">Every organization has a story.<br/>Most do not know how to tell it. We do.</p><div className="hero-actions"><Action light>Bring Us a Challenge</Action><Link className="quiet-link" href="/expertise">Explore Our Expertise <ArrowUpRight size={17}/></Link></div></div><div className="hero-signal" aria-hidden="true"><span>A DIFFERENT PERSPECTIVE<br/>CHANGES EVERYTHING.</span><span>IDEA → IMPACT → INFLUENCE</span></div></div><div className="hero-bottom wrap"><span>A BOUTIQUE STRATEGIC COMMUNICATIONS & CREATIVE AGENCY</span><a href="#intro">STEP INSIDE <ArrowDown size={15}/></a></div></section>
<section id="intro" className="section wrap intro"><Reveal><span className="eyebrow">01 / THE WAY WE THINK</span></Reveal><Reveal><h2>Communication isn’t<br/>an afterthought.<br/><em>It’s infrastructure.</em></h2><div className="intro-copy"><h3>Unlocking Your Potential Through Communication</h3><p>We turn complex ideas, development work and organizational ambitions into narratives that people understand, remember and act on.</p><p>Strategy, storytelling, creativity, technology and engagement. Connected, so every story works harder.</p><Link className="text-link" href="/about">Step into the House of Ideas <ArrowUpRight size={17}/></Link></div></Reveal></section>
<section className="section expertise-preview"><div className="wrap"><Reveal><SectionHeading eyebrow="02 / OUR EXPERTISE" title="Many disciplines. One clear purpose.">The right thinking. The right craft. The right connection.</SectionHeading></Reveal><div className="services-grid">{services.map((s,i)=><Reveal key={s.slug}><ServiceCard service={s} index={i}/></Reveal>)}</div></div></section>
<section className="manifesto"><div className="wrap"><span className="eyebrow">GREAT WORK BEGINS WITH A QUESTION.</span><Reveal><h2>Bring us a challenge.<br/><span>Bring us a half-formed idea.</span><br/>Bring us the story you have<br className="desktop-break"/> not figured out how to tell yet.</h2></Reveal><div className="manifesto-bottom"><p>Give us a blank canvas.<br/><em>We will make it unforgettable.</em></p><Link className="circle-link" aria-label="Bring us your challenge" href="/contact"><ArrowUpRight size={30}/></Link></div></div></section>
<section className="section wrap"><div className="section-top"><SectionHeading eyebrow="03 / EXPERIENCE THAT COUNTS" title="Thinking big. Making it matter."/><Link href="/experience" className="text-link">Explore our experience <ArrowUpRight size={18}/></Link></div><div className="stats-grid">{stats.map(s=><Reveal key={s.value}><StatBlock stat={s}/></Reveal>)}</div><p className="section-note">Experience brought to Ladder Point by its leadership.</p></section>
<section className="process-section section"><div className="wrap"><SectionHeading eyebrow="04 / THE LADDER POINT MODEL" title="A clear path from idea to impact."/><ProcessFlow/></div></section>
<section className="section wrap"><div className="section-top"><SectionHeading eyebrow="05 / WAYS TO WORK TOGETHER" title="Built around your ambition."/><Link className="text-link" href="/packages">Explore all packages <ArrowUpRight size={18}/></Link></div><div className="packages-grid">{packages.map((p,i)=><PackageCard key={p.name} item={p} index={i}/>)}</div><p className="section-note">Packages can be tailored to your context. <Link href="/contact">Start a Conversation ↗</Link></p></section>
<section className="leadership section"><div className="wrap leadership-grid"><div className="portrait-placeholder" aria-label="Doreen Hove portrait area"><span className="portrait-monogram">dh.</span><span className="eyebrow">A HUMAN PERSPECTIVE.</span></div><div><span className="eyebrow">06 / MEET THE THINKING BEHIND THE WORK</span><h2>Strategy with depth.<br/><em>Stories with soul.</em></h2><h3>Doreen Hove</h3><span className="role">Co-Founder & Lead Consultant</span><p>Doreen brings more than 18 years of experience to the intersection of strategic communications, storytelling and development. Her experience includes communications leadership for a development portfolio exceeding $300 million annually.</p><Link className="text-link" href="/about#leadership">Meet our leadership <ArrowUpRight size={17}/></Link></div></div></section><CTASection/></>}
