import Link from 'next/link';
import { ArrowUpRight, ArrowRight } from 'lucide-react';
import { packages, services, stats } from '@/content/site';
export function Action({ children, href = '/contact', light = false }: { children: React.ReactNode; href?: string; light?: boolean }) { return <Link className={`button ${light ? 'light' : ''}`} href={href}>{children}<ArrowUpRight size={18}/></Link> }
export function SectionHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children && <p>{children}</p>}</div> }
export function Ladder({ large = false }: { large?: boolean }) { return <svg className={large ? 'ladder-art' : 'brand-mark'} viewBox="0 0 300 400" fill="none" aria-hidden="true"><path d="M60 380V100L240 20V300M60 100L240 20M60 155L240 75M60 210L240 130M60 265L240 185M60 320L240 240M60 375L240 295" stroke="currentColor" strokeWidth={large ? 1 : 15}/>{large && <><path d="M20 398V82L240 -16M100 400V118L280 38V320M0 375L300 242M0 320L300 187M0 265L300 132" stroke="currentColor" strokeOpacity=".2"/><circle cx="240" cy="20" r="5" fill="currentColor"/></>}</svg> }
export function Hero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="page-hero wrap"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p><span className="hero-index">LADDER POINT / THE HOUSE OF IDEAS</span></section> }
export function ServiceCard({ service, index }: { service: typeof services[number]; index: number }) { return <Link className="service-card" href={`/expertise#${service.slug}`}><span className="small-number">0{index + 1}</span><div><h3>{service.name}</h3><p>{service.short}</p><span className="text-link">Discover more <ArrowUpRight size={16}/></span></div></Link> }
export function StatBlock({ stat }: { stat: typeof stats[number] }) { return <div className="stat"><strong>{stat.value}</strong><span>{stat.label}</span><p>{stat.detail}</p></div> }
export function PackageCard({ item, index }: { item: typeof packages[number]; index: number }) { return <Link className="package-card" href={`/packages#package-${index}`}><span className="eyebrow">0{index + 1} / BUILT FOR YOUR CONTEXT</span><h3>{item.name}<span>Package</span></h3><p>{item.audience}</p><ArrowUpRight className="package-arrow" size={25}/></Link> }
export function ProcessFlow() { return <div className="process">{['Insight','Strategy','Story','Creation','Engagement','Impact'].map((step,i)=><div key={step}><span className="process-num">0{i+1}</span><h3>{step}</h3><p>{['We research the problem.','We build the strategy.','We craft the message.','We photograph the story. We film it. We animate it.','We take it digital.','We make sure it reaches the people who matter.'][i]}</p>{i<5 && <ArrowRight size={18}/>}</div>)}</div> }
export function CTASection() { return <section className="cta"><div className="wrap"><span className="eyebrow">LET’S MAKE SOMETHING MATTER</span><h2>Your next story<br/>starts <em>here.</em></h2><div className="cta-bottom"><p>Bring us the challenge. We will help you turn it into something people can understand, remember and act on.</p><Action light>Start a Conversation</Action></div></div></section> }
